naam = str(input("wat is u voor en achter naam?: "))
adres = str(input("wat is u adres?: "))
postcode = str(input("wat is u postcode?: "))
woonplaats = str(input("wat is u woonplaats?: "))

print(" ----------------------------------------------------")
print(f"|  Naam      : {naam}                ")
print(f"|  Adres     : {adres}           ")
print(f"|  Postcode  : {postcode}                         ")
print(f"|  Woonplaats: {woonplaats}                          ")
print(" ----------------------------------------------------")